---
- name: Setup teleport startup script
  copy:
    src: "files/teleport"    
    dest: "/etc/init.d/teleport"
    force: yes
    owner: root
    group: root
    mode: 0755
  notify: restart teleport